import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import './globals.css';
import { DINRound } from './styles/font';

export const metadata: Metadata = {
  title: 'Doulingo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={(cn('h-screen w-screen'), DINRound.className)}>{children}</body>
    </html>
  );
}
